plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'com.gradle.plugin-publish' version '1.2.1'
}

group = 'io.github.vansencool'
version = '1.0.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.hierynomus:sshj:0.39.0'
}

gradlePlugin {
    website = 'https://github.com/vansencool/dexternally'
    vcsUrl = 'https://github.com/vansencool/dexternally.git'

    plugins {
        dexternally {
            id = 'io.github.vansencool.dexternally'
            displayName = 'DExternally'
            description = 'A simple gradle plugin to upload (build) files to SFTP'
            tags.addAll('sftp', 'uploader', 'deploy')
            implementationClass = 'io.github.vansencool.dexternally.DExternallyPlugin'
        }
    }
}